import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/Providers";
import { ModalProvider } from "@/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Snippets App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <ModalProvider> */}
          {children}
          {/* </ModalProvider> */}
        </Providers>
      </body>
    </html>
  );
}
